name: aws-v5
on:
  push:
    branches:
      - main

# https://github.com/actions/setup-java
# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.
jobs:
  build:  # job의 이름 내가 정함
    runs-on: ubuntu-latest  # EC2처럼 도커 생성(우분투)
    steps:  # - 로 구분 (시퀀스라 한다)
      - name: Checkout  # name은 안적어도 되긴하다. 그래도 구분되도록
        uses: actions/checkout@v3 # action : 스크립트의 모임. 해당 표기를 검색하면 나온다 
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - name: Permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build